/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './logout.component';
import * as i2 from './auth.service';
import * as i3 from '@angular/router';
const styles_LogoutComponent:any[] = ([] as any[]);
export const RenderType_LogoutComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_LogoutComponent,data:{}});
export function View_LogoutComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted(-1,(null as any),['\n        '])),(_l()(),i0.ɵeld(1,
      0,(null as any),(null as any),4,'div',[['class','col-md-8 col-md-offset-2']],
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i0.ɵted(-1,(null as any),['\n            '])),(_l()(),i0.ɵeld(3,0,(null as any),
      (null as any),1,'button',[['class','btn btn-danger']],(null as any),[[(null as any),
          'click']],(_v,en,$event) => {
        var ad:boolean = true;
        var _co:i1.LogoutComponent = _v.component;
        if (('click' === en)) {
          const pd_0:any = ((<any>_co.onLogout()) !== false);
          ad = (pd_0 && ad);
        }
        return ad;
      },(null as any),(null as any))),(_l()(),i0.ɵted(-1,(null as any),['Logout'])),
      (_l()(),i0.ɵted(-1,(null as any),['\n        '])),(_l()(),i0.ɵted(-1,(null as any),
          ['\n    ']))],(null as any),(null as any));
}
export function View_LogoutComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),1,'app-logout',
      ([] as any[]),(null as any),(null as any),(null as any),View_LogoutComponent_0,
      RenderType_LogoutComponent)),i0.ɵdid(1,49152,(null as any),0,i1.LogoutComponent,
      [i2.AuthService,i3.Router],(null as any),(null as any))],(null as any),(null as any));
}
export const LogoutComponentNgFactory:i0.ComponentFactory<i1.LogoutComponent> = i0.ɵccf('app-logout',
    i1.LogoutComponent,View_LogoutComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovV29ya2luZy9hbmd1bGFyLW5vZGUvYXNzZXRzL2FwcC9hdXRoL2xvZ291dC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovV29ya2luZy9hbmd1bGFyLW5vZGUvYXNzZXRzL2FwcC9hdXRoL2xvZ291dC5jb21wb25lbnQudHMiLCJuZzovLy9DOi9Xb3JraW5nL2FuZ3VsYXItbm9kZS9hc3NldHMvYXBwL2F1dGgvbG9nb3V0LmNvbXBvbmVudC50cy5Mb2dvdXRDb21wb25lbnQuaHRtbCIsIm5nOi8vL0M6L1dvcmtpbmcvYW5ndWxhci1ub2RlL2Fzc2V0cy9hcHAvYXV0aC9sb2dvdXQuY29tcG9uZW50LnRzLkxvZ291dENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxuICAgICAgICA8ZGl2IGNsYXNzPVwiY29sLW1kLTggY29sLW1kLW9mZnNldC0yXCI+XG4gICAgICAgICAgICA8YnV0dG9uIGNsYXNzPVwiYnRuIGJ0bi1kYW5nZXJcIiAoY2xpY2spPVwib25Mb2dvdXQoKVwiPkxvZ291dDwvYnV0dG9uPlxuICAgICAgICA8L2Rpdj5cbiAgICAiLCI8YXBwLWxvZ291dD48L2FwcC1sb2dvdXQ+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7OztvQkNBQSxrREFDUTtNQUFBO01BQUEsd0VBQXNDO2FBQUEsdUNBQ2xDO01BQUE7VUFBQTtRQUFBO1FBQUE7UUFBK0I7VUFBQTtVQUFBO1FBQUE7UUFBL0I7TUFBQSxnQ0FBb0Q7TUFBZSxrREFDakU7VUFBQTs7O29CQ0hkO01BQUE7Z0NBQUEsVUFBQTtNQUFBOzs7In0=
