/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './header.component.ngfactory';
import * as i2 from './header.component';
import * as i3 from '@angular/router';
import * as i4 from './errors/error.component.ngfactory';
import * as i5 from './errors/error.component';
import * as i6 from './errors/error.service';
import * as i7 from './app.component';
const styles_AppComponent:any[] = ([] as any[]);
export const RenderType_AppComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,styles:styles_AppComponent,
    data:{}});
export function View_AppComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted(-1,(null as any),['\n'])),(_l()(),i0.ɵted(-1,(null as any),
      ['\n\n'])),(_l()(),i0.ɵeld(2,0,(null as any),(null as any),9,'div',[['class',
      'container']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted(-1,(null as any),['\n    '])),(_l()(),i0.ɵeld(4,0,(null as any),
          (null as any),1,'app-header',([] as any[]),(null as any),(null as any),(null as any),
          i1.View_HeaderComponent_0,i1.RenderType_HeaderComponent)),i0.ɵdid(5,49152,
          (null as any),0,i2.HeaderComponent,([] as any[]),(null as any),(null as any)),
      (_l()(),i0.ɵted(-1,(null as any),['\n    '])),(_l()(),i0.ɵeld(7,0,(null as any),
          (null as any),0,'hr',([] as any[]),(null as any),(null as any),(null as any),
          (null as any),(null as any))),(_l()(),i0.ɵted(-1,(null as any),['\n    '])),
      (_l()(),i0.ɵeld(9,16777216,(null as any),(null as any),1,'router-outlet',([] as any[]),
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      i0.ɵdid(10,212992,(null as any),0,i3.RouterOutlet,[i3.ChildrenOutletContexts,
          i0.ViewContainerRef,i0.ComponentFactoryResolver,[8,(null as any)],i0.ChangeDetectorRef],
          (null as any),(null as any)),(_l()(),i0.ɵted(-1,(null as any),['\n'])),(_l()(),
          i0.ɵted(-1,(null as any),['\n'])),(_l()(),i0.ɵeld(13,0,(null as any),(null as any),
          1,'app-error',([] as any[]),(null as any),(null as any),(null as any),i4.View_ErrorComponent_0,
          i4.RenderType_ErrorComponent)),i0.ɵdid(14,114688,(null as any),0,i5.ErrorComponent,
          [i6.ErrorService],(null as any),(null as any)),(_l()(),i0.ɵted(-1,(null as any),
          ['\n']))],(_ck,_v) => {
    _ck(_v,10,0);
    _ck(_v,14,0);
  },(null as any));
}
export function View_AppComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),1,'my-app',([] as any[]),
      (null as any),(null as any),(null as any),View_AppComponent_0,RenderType_AppComponent)),
      i0.ɵdid(1,49152,(null as any),0,i7.AppComponent,([] as any[]),(null as any),
          (null as any))],(null as any),(null as any));
}
export const AppComponentNgFactory:i0.ComponentFactory<i7.AppComponent> = i0.ɵccf('my-app',
    i7.AppComponent,View_AppComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovV29ya2luZy9hbmd1bGFyLW5vZGUvYXNzZXRzL2FwcC9hcHAuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1dvcmtpbmcvYW5ndWxhci1ub2RlL2Fzc2V0cy9hcHAvYXBwLmNvbXBvbmVudC50cyIsIm5nOi8vL0M6L1dvcmtpbmcvYW5ndWxhci1ub2RlL2Fzc2V0cy9hcHAvYXBwLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovV29ya2luZy9hbmd1bGFyLW5vZGUvYXNzZXRzL2FwcC9hcHAuY29tcG9uZW50LnRzLkFwcENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjwhLS0gQnVpbHQgaW4gZGlyZWN0aXZlIHdoaWNoIGhvbGRzIHRoZSByb3V0aW5nIHRlbXBsYXRlcyAtLT5cclxuPCEtLSA8cm91dGVyLW91dGxldD48L3JvdXRlci1vdXRsZXQ+IGJ5IGRlZmF1bHQgd2lsbCByZWFkIHRoZSByb3V0aW5nIGluc3RydWN0aW9ucyBmcm9tIHRoZSBtYWluIHJvdXRpbmcgbW9kdWxlIC0tPlxyXG5cclxuPGRpdiBjbGFzcz1cImNvbnRhaW5lclwiPlxyXG4gICAgPGFwcC1oZWFkZXI+PC9hcHAtaGVhZGVyPlxyXG4gICAgPGhyPlxyXG4gICAgPHJvdXRlci1vdXRsZXQ+PC9yb3V0ZXItb3V0bGV0PlxyXG48L2Rpdj5cclxuPGFwcC1lcnJvcj48L2FwcC1lcnJvcj5cclxuIiwiPG15LWFwcD48L215LWFwcD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7OztvQkNBNkQsMENBQ3NEO01BQUEsV0FFbkg7TUFBQTtNQUF1Qiw4Q0FDbkI7VUFBQTtpRUFBQSxVQUFBO1VBQUE7TUFBeUIsOENBQ3pCO1VBQUE7VUFBQSw4QkFBSTtNQUNKO1VBQUE7YUFBQTswREFBQTtVQUFBLDZCQUErQiwwQ0FDN0I7aUJBQUEsMkJBQ047VUFBQTtzQ0FBQSxVQUFBO1VBQUEsK0NBQXVCO1VBQUE7SUFGbkI7SUFFSjs7OztvQkNSQTtNQUFBO2FBQUE7VUFBQTs7OyJ9
